import fs from "node:fs";import path from "node:path";import url from "node:url";
const here=path.dirname(url.fileURLToPath(import.meta.url)),root=path.resolve(here,"..");let checks=0,failures=0;const expect=(ok,msg)=>{checks++;if(!ok){failures++;console.error(`FAIL: ${msg}`);}};const read=(p)=>fs.readFileSync(path.join(root,p),"utf8");
const moduleJson=JSON.parse(read("module.json"));expect(moduleJson.id==="cpr-netrunning-next","experimental module id changed");expect(["0.3.0","0.4.0","0.5.0"].includes(moduleJson.version),"module is older than the 0.3 cockpit baseline");for(const m of ["scripts/request-v03.js","scripts/ux-v03.js"])expect(moduleJson.esmodules.includes(m),`${m} is not loaded`);expect(moduleJson.styles.includes("styles/v03.css"),"v03 CSS is not loaded");
const projection=read("scripts/projection.js");expect(!projection.includes("dv:node.dv"),"player projection appears to expose node DV");expect(!projection.includes("gmNotes:node.gmNotes"),"player projection appears to expose GM notes directly");
const plain=read("scripts/plain-interface-v03.js");expect(plain.includes("CPRInterfaceRoll"),"Going Quiet does not use native CPRInterfaceRoll");expect(!plain.includes('rollInterface(actor, "scanner"'),"Scanner is still substituted for plain Interface");expect(plain.includes("allActions"),"plain Interface Check lost universal action modifiers");
const request=read("scripts/request-v03.js");expect(request.includes("rollPlainInterfaceV03"),"Going Quiet controller is not using the plain Interface bridge");expect(request.includes("total) > Number(watcher.total"),"Quiet Jack tie handling is not strict");
const ux=read("scripts/ux-v03.js");for(const word of ["fitMap","Space+drag","programs-toggle","inspectorCollapsed","focusMode"])expect(ux.includes(word),`UX feature missing: ${word}`);
const css=read("styles/v03.css");expect(css.includes("v03-inspector-collapsed"),"inspector collapse CSS missing");expect(css.includes("v03-focus"),"focus mode CSS missing");expect(css.includes("prefers-reduced-motion"),"reduced-motion fallback missing");expect(css.includes(":focus-visible"),"keyboard focus styling missing");
console.log(`Lab 0.3 baseline checks: ${checks}, failures: ${failures}`);process.exit(failures?1:0);
