/* Netrunning Lab 0.5 — contextual Black ICE encounter UI.
 * No permanent combat sidebar: encounter prompts appear only while the runtime
 * is actually waiting for a RED SPEED/Cloak resolution or a failed-SPEED effect.
 */
import { ID } from "./store.js";
import { readMyProjection, sanitizeArchitecture } from "./projection.js";
import { rollInterface } from "./runner-profile.js";

const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const RU = () => String(game.i18n?.lang || "en").toLowerCase().startsWith("ru");
const T = () => RU() ? {
  speed:"ПРОВЕРКА СКОРОСТИ", stealth:"СКРЫТНОЕ СТОЛКНОВЕНИЕ", free:"БЕСПЛАТНО",
  rollSpeed:"Бросить SPEED", rollCloak:"Cloak против PER",
  effect:"ЭФФЕКТ BLACK ICE ДОЛЖЕН СРАБОТАТЬ", effectHint:"Провал проверки означает немедленный эффект Black ICE. Мастер применяет его по карточке/листу ICE и подтверждает продолжение.",
  resolved:"Эффект применён", open:"Открыть лист", pursuit:"ПРЕСЛЕДОВАНИЕ", target:"Взять в цель", targeted:"ЦЕЛЬ", waiting:"Ожидание мастера",
  threat:"BLACK ICE РЕАГИРУЕТ", speedHelp:"Interface + бонусы SPEED + 1d10 против SPD Black ICE. Ничья спасает Нетраннера от немедленного эффекта.",
  stealthHelp:"Interface + бонусы Cloak + 1d10 против PER Black ICE. Нужно превзойти ICE; ничья раскрывает Нетраннера.",
  slideTitle:"Куда соскользнуть?", slideHint:"Успешный Slide немедленно перемещает Нетраннера на выбранный соседний этаж. Через NET-препятствие Slide не проходит.", slideNoRoute:"Нет доступного соседнего этажа для Slide.", encrypted:"ЗАШИФРОВАНО"
} : {
  speed:"SPEED CHECK", stealth:"STEALTH ENCOUNTER", free:"FREE",
  rollSpeed:"Roll SPEED", rollCloak:"Cloak vs PER",
  effect:"BLACK ICE EFFECT MUST RESOLVE", effectHint:"A failed check means the Black ICE immediate effect resolves now. The GM applies its card/sheet effect, then confirms continuation.",
  resolved:"Effect resolved", open:"Open sheet", pursuit:"PURSUIT", target:"Target", targeted:"TARGET", waiting:"Waiting for GM",
  threat:"BLACK ICE REACTS", speedHelp:"Interface + SPEED bonuses + 1d10 vs Black ICE SPD. A tie protects the Netrunner from the immediate effect.",
  stealthHelp:"Interface + Cloak bonuses + 1d10 vs Black ICE PER. The Netrunner must beat the ICE; a tie means detection.",
  slideTitle:"Slide where?", slideHint:"A successful Slide immediately moves the Netrunner to the chosen adjacent floor. NET obstructions cannot be crossed by Slide.", slideNoRoute:"No accessible adjacent floor is available for Slide.", encrypted:"ENCRYPTED"
};

function rootFor(app, html) { const host=html?.[0]||html; return host?.matches?.(".crnsl-root")?host:host?.querySelector?.(".crnsl-root")||app?.element?.[0]?.querySelector?.(".crnsl-root")||null; }
function findIce(arch, ref) {
  const id=String(ref||"").startsWith("ice:")?String(ref).slice(4):"";
  for(const node of arch?.nodes||[]){const entity=(node.entities||[]).find((e)=>e.kind==="blackice"&&e.id===id);if(entity)return{ref:`ice:${entity.id}`,label:entity.label||"Black ICE",actorId:entity.actorId||"",nodeId:node.id};}
  return{ref:String(ref||""),label:"Black ICE",actorId:"",nodeId:""};
}

async function viewFor(app) {
  if(!game.user.isGM){const projection=readMyProjection();return projection?{runner:projection.runner,projection,state:null,arch:null}:{runner:null};}
  const state=await app.store.getRuntime();const runner=state.runners?.[state.activeRunnerId]||Object.values(state.runners||{})[0]||null;const arch=state.activeArchitectureId?await app.store.get(state.activeArchitectureId):null;if(!runner||!arch)return{runner:null,state,arch};
  if(app.preview){const projection=sanitizeArchitecture(arch,state,runner.id);return{runner:projection?.runner||null,projection,state,arch};}
  const pendingEncounters=Object.values(state.encounters||{}).filter((e)=>e.runnerId===runner.id&&e.status==="pending").map((e)=>({id:e.id,ref:e.ref,name:e.name,mode:e.mode,nodeId:e.nodeId,actorId:e.actorId}));
  const freeIceEffects=Object.values(state.freeIceEffects||{}).filter((e)=>e.runnerId===runner.id);const engagedIce=(runner.engagedIceRefs||[]).map((ref)=>findIce(arch,ref));
  return{runner:{...runner,pendingEncounters,freeIceEffects,engagedIce},state,arch};
}

function encounterHtml(encounter,count){const c=T(),stealth=encounter.mode==="stealth";return`<div class="crnsl-v05-encounter ${stealth?"stealth":"speed"}" data-v05-encounter-id="${esc(encounter.id)}"><span class="v05-threat-icon"><i class="fas ${stealth?"fa-user-secret":"fa-skull-crossbones"}"></i></span><div class="v05-threat-copy"><small>${esc(c.threat)}${count>1?` · ${count}`:""}</small><strong>${esc(encounter.name||"Black ICE")}</strong><span>${esc(stealth?c.stealth:c.speed)} · ${esc(c.free)}</span><em>${esc(stealth?c.stealthHelp:c.speedHelp)}</em></div><button type="button" data-v05-action="encounter-roll" data-encounter-id="${esc(encounter.id)}" data-mode="${stealth?"stealth":"speed"}"><i class="fas fa-dice-d10"></i>${esc(stealth?c.rollCloak:c.rollSpeed)}</button></div>`;}
function effectHtml(effect,gm){const c=T();return`<div class="crnsl-v05-effect" data-v05-effect-id="${esc(effect.id)}"><span class="v05-effect-icon"><i class="fas fa-bolt"></i></span><div><small>${esc(c.effect)}</small><strong>${esc(effect.name||"Black ICE")}</strong><p>${esc(c.effectHint)}</p></div><div class="v05-effect-actions">${gm&&effect.actorId?`<button type="button" data-v05-action="open-ice" data-actor-id="${esc(effect.actorId)}"><i class="fas fa-up-right-from-square"></i>${esc(c.open)}</button>`:""}${gm?`<button type="button" class="confirm" data-v05-action="ack-effect" data-effect-id="${esc(effect.id)}"><i class="fas fa-check"></i>${esc(c.resolved)}</button>`:`<span>${esc(c.waiting)}</span>`}</div></div>`;}
function pursuitHtml(runner){const list=runner?.engagedIce||[];if(!list.length)return"";const c=T();return`<div class="crnsl-v05-pursuit"><span class="v05-pursuit-label"><i class="fas fa-link"></i>${esc(c.pursuit)}</span><div class="v05-pursuit-list">${list.map((ice)=>{const target=runner.targetRef===ice.ref;return`<button type="button" class="v05-pursuit-chip ${target?"targeted":""}" data-v05-action="target-ice" data-ref="${esc(ice.ref)}" title="${esc(c.target)}"><i class="fas fa-snowflake"></i><span>${esc(ice.label)}</span>${target?`<b>${esc(c.targeted)}</b>`:""}</button>`;}).join("")}</div></div>`;}

function blockNormalActions(root,blocked){root.classList.toggle("v05-encounter-blocking",blocked);for(const button of root.querySelectorAll('[data-action="move"],[data-action="ability"],[data-action="program-toggle"],[data-action="control-execute"],[data-action="jack-out"]')){if(blocked){button.dataset.v05WasDisabled=button.disabled?"1":"0";button.disabled=true;}}if(blocked&&!root.dataset.v05DblBlock){root.dataset.v05DblBlock="1";root.addEventListener("dblclick",(event)=>{if(root.classList.contains("v05-encounter-blocking")&&event.target.closest(".crnsl-node")){event.preventDefault();event.stopImmediatePropagation();}},true);}}
async function currentRunnerId(app){if(!game.user.isGM)return readMyProjection()?.runner?.id||"";const state=await app.store.getRuntime();return state.activeRunnerId||"";}

async function doEncounterRoll(app,encounterId,mode,event){const runnerId=await currentRunnerId(app);const grant=await app.transport.request({op:"beginEncounter",runnerId,encounterId});const actor=await fromUuid(grant.actorUuid);if(!actor)throw new Error("Runner Actor is unavailable.");const ability=mode==="stealth"?"cloak":"speed";const rolled=await rollInterface(actor,ability,event,{grantToken:grant.token});if(!rolled?.messageId){await app.transport.request({op:"cancelRoll",token:grant.token,runnerId});return;}const result=await app.transport.request({op:"completeEncounter",runnerId,token:grant.token,messageId:rolled.messageId});ui.notifications[result?.success?"info":"warn"](result?.success?(RU()?"Столкновение пройдено.":"Encounter cleared."):(RU()?"Black ICE получает немедленный эффект.":"Black ICE immediate effect is pending."));}

async function slideProjection(app){if(!game.user.isGM)return readMyProjection();const state=await app.store.getRuntime();const runner=state.runners?.[state.activeRunnerId]||null;const arch=state.activeArchitectureId?await app.store.get(state.activeArchitectureId):null;return runner&&arch?sanitizeArchitecture(arch,state,runner.id):null;}
async function chooseSlideDestination(app){const projection=await slideProjection(app),c=T();const choices=(projection?.moves||[]).filter((m)=>m.ok);if(!choices.length)throw new Error(c.slideNoRoute);const options=choices.map((m)=>{const node=(projection.nodes||[]).find((n)=>n.id===m.id);const label=node?.unknown?c.encrypted:(node?.label||"NET Floor");return`<option value="${esc(m.id)}">${esc(label)}</option>`;}).join("");return Dialog.prompt({title:c.slideTitle,content:`<p>${esc(c.slideHint)}</p><div class="form-group"><label>${esc(c.slideTitle)}</label><select name="destination">${options}</select></div>`,callback:(html)=>String(html.find('select[name="destination"]').val()||"")});}
async function doSlide(app,event){const runnerId=await currentRunnerId(app),destinationNodeId=await chooseSlideDestination(app);if(!destinationNodeId)return;const grant=await app.transport.request({op:"beginAbility",runnerId,ability:"slide",destinationNodeId});const actor=await fromUuid(grant.actorUuid);if(!actor)throw new Error("Runner Actor is unavailable.");const rolled=await rollInterface(actor,"slide",event,{grantToken:grant.token});if(!rolled?.messageId){await app.transport.request({op:"cancelRoll",token:grant.token,runnerId});return;}const result=await app.transport.request({op:"completeAbility",runnerId,token:grant.token,messageId:rolled.messageId});ui.notifications[result?.success?"info":"warn"](result?.success?(RU()?"Slide успешен: преследование разорвано.":"Slide succeeded: pursuit broken."):(RU()?"Slide провален: Black ICE продолжает преследование.":"Slide failed: Black ICE keeps pursuing."));}

async function enhance(app,html){if(app?.options?.id!=="crnsl-window")return;const root=rootFor(app,html);if(!root)return;const view=await viewFor(app),runner=view.runner;root.querySelectorAll(".crnsl-v05-encounter,.crnsl-v05-effect,.crnsl-v05-pursuit").forEach((el)=>el.remove());const pending=runner?.pendingEncounters||[],effects=runner?.freeIceEffects||[];const anchor=root.querySelector(".crnsl-action-dock")||root.querySelector(".crnsl-build-dock");if(anchor&&!root.querySelector(".crnsl-build-dock")){if(effects[0])anchor.insertAdjacentHTML("beforebegin",effectHtml(effects[0],game.user.isGM&&!app.preview));else if(pending[0])anchor.insertAdjacentHTML("beforebegin",encounterHtml(pending[0],pending.length));const pursuit=pursuitHtml(runner);if(pursuit)anchor.insertAdjacentHTML("afterbegin",pursuit);}const blocked=pending.length>0||effects.length>0;blockNormalActions(root,blocked);root.querySelector(".crnsl-node.current")?.classList.toggle("v05-under-pursuit",(runner?.engagedIce||[]).length>0);root.dataset.v05Pending=String(pending.length);root.dataset.v05Effects=String(effects.length);root.dataset.v05Engaged=(runner?.engagedIceRefs||[]).join("|");root.dataset.v05Slid=(runner?.slidIceRefs||[]).join("|");const footer=root.querySelector(".crnsl-footer span:first-child");if(footer)footer.innerHTML="<strong>LAB</strong> v0.5.0";
  if(!root.dataset.v05Events){root.dataset.v05Events="1";root.addEventListener("click",(event)=>{const slideButton=event.target.closest('[data-action="ability"][data-ability="slide"]');if(slideButton){event.preventDefault();event.stopImmediatePropagation();doSlide(app,event).catch((error)=>{console.error(`${ID} | v05 slide`,error);ui.notifications.error(error.message);});return;}const button=event.target.closest("[data-v05-action]");if(!button)return;event.preventDefault();event.stopPropagation();(async()=>{const action=button.dataset.v05Action;if(action==="encounter-roll")await doEncounterRoll(app,button.dataset.encounterId,button.dataset.mode,event);else if(action==="ack-effect"){const runnerId=await currentRunnerId(app);await app.transport.request({op:"ackIceEffect",runnerId,effectId:button.dataset.effectId});}else if(action==="open-ice"){game.actors?.get(button.dataset.actorId)?.sheet?.render(true);}else if(action==="target-ice"){const runnerId=await currentRunnerId(app);await app.transport.request({op:"setTarget",runnerId,ref:button.dataset.ref||""});}})().catch((error)=>{console.error(`${ID} | v05 ui`,error);ui.notifications.error(error.message);});},true);}
}
Hooks.on("renderApplication",(app,html)=>enhance(app,html).catch((e)=>console.debug(`${ID} | v05 render`,e)));Hooks.on("renderNetrunningLabApp",(app,html)=>enhance(app,html).catch((e)=>console.debug(`${ID} | v05 render`,e)));
